### ISSUE TITLE
Medium repos / time for build & test

### ISSUE THREAD

**Issue by fforjan** [MicrosoftDocs/devops-resource-center#1]
I'm really surprised that you can achieve 10minutes build and 5 minutes unit tests for medium type repository.
Do you have any discussion / samples of how you run/organize your build/tests, machines etc.. (preferably in the context of a desktop application) ?
Typically, if I look at WinUI : they just spend 40 minutes into the unit tests :
https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=58186&view=logs&jobId=d79de4a2-8ffa-524a-a762-f0c23acfce7b&j=d79de4a2-8ffa-524a-a762-f0c23acfce7b&t=b3aafff6-6881-52e7-ef07-fb7d641a9fa2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 351f23cd-0f45-4f9e-6907-7e25b31fe4b4
* Version Independent ID: ec7c8359-810d-79e7-03b3-8d5ddab31aee
* Content: [Git at Scale - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/git/git-at-scale#feedback)
* Content Source: [docs/git/git-at-scale.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/git/git-at-scale.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **sanoursa**

**Comment by InternetPseudonym** [comment]
tbh : 40 minutes of unit testing is a surefire sign that the tests are completely bonkers. If a single test does not finish within SECONDS you might want to redesign it because unit tests should test SINGLE UNITS and not complete applications.

Even 10 minutes are rather ... weird and most likely caused by faulty test design as long as there arent tens of thousands of tests

**Comment by fforjan** [comment]
@InternetPseudonym please have a look at the Microsoft project doing 40 minutes and why you think this is wrong. 
Altought I fully agree with you from a ideal situation, some projects are a bit more complex, have history (10,  15 or more years) which means do not fit fully in this category.

**Comment by InternetPseudonym** [comment]
neither the project history nor complexity are reasons for having erroneous test-code. Technically, reasons for bad code do not exist - they never did - literally all of them actually need to be translated into "lazyness" and/or "lack of knowledge / skills", the former of which sometimes can be attributed to management, combined with "fear of the unknown" and "religious tech-fanatism". Sorry. Thats the cold, uncomfortable truth of reality.

Also the unchangeable truth : unit tests need to test single units. If they test more than one they cannot be called unit test anymore. Some like to call them integration tests ... which is exactly what they are

**Comment by fforjan** [comment]
@InternetPseudonym  Sure. let's call the integration tests. So let's call them technical debt. Let's call them whatever you want. Let's call it whatever you want.
Let's have a look at https://dev.azure.com/dnceng/public/_build/results?buildId=501238&view=results
![image](https://user-images.githubusercontent.com/601810/73419815-60ef8a80-42d5-11ea-9a44-e75c12d8b4ed.png)
Is roslyn analyzer a wrong example ? why is it that long then ? 
Do you have any link to a projects of a nice size doing their unit tests in less than 10 minutes, preference of mix of C++/C# with desktop?

**Comment by InternetPseudonym** [comment]
Yes of course - quite a lot. Unfortunately, even sharing a single piece of code would get me arrested. Also: Your examples of bad code do not change facts, no matter how many you drag up. 

Yes, there are **a lot** of developers who arent actually that good at their job _(possibly including myself, of course)_, if that is what you wanted to point out. Absolutely correct.

**Comment by fforjan** [comment]
@InternetPseudonym then definition of the medium repository is incorrect for me. I may agree from a  ideal point of view - although i do not see how a project with 400 peoples will only take 10 minutes to build after a couple of year but from all examples I have seen so far, from me or from Microsoft, this definition is incorrect.

**Comment by InternetPseudonym** [comment]
Sorry, that doesnt make much sense - projects are not required to build within 10 minutes or so; UNIT TESTS are _(required to RUN within seconds each)_. I recommend looking into topics like "build pipeline", there is much to discover.

Also : team size literally has no effect on standards and definitions - if a team chooses to throw them overboard just because its currently inconvenient and because its _"too much work_" ... well ... such a team is completely defective in more ways than one

If you want to dive into these post-90s paradigms please look up "CI/CD", "agile development" and maybe the book "clean code" by Robert C Martin. Enjoy.

**Comment by fforjan** [comment]
we are discussing about that :
![image](https://user-images.githubusercontent.com/601810/73460922-2cf48380-432e-11ea-80a0-ac2c309140f1.png)
PS: I know exactlt what is CI/CD, agile development. 
You may want to add Scaled Agile Development to your list.
